### ISSUE TITLE
Selectable Z zero location

### ISSUE THREAD

**Issue by hoverdj** [AndrewEllis93/Pressure_Linear_Advance_Tool#11]
My printer is a FlashForge Creator Pro (MakerBot replica, basically) that has the bed rising and lowering for the Z axis. Zero is at top.

When running your code, it appears it assumes Z0 is at the bottom, as is the case with most printers (I think). 

It would be nice if your tool could allow for that as an option. Maybe it does and I'm just not seeing it?

Thanks for your consideration!
D-

**Comment by AndrewEllis93** [comment]
Currently it does not have that - but I don't think it would be too difficult to add, pretty much just invert all the Z coordinates, right?

**Comment by hoverdj** [comment]
Yes, that is the way I understand it. ThanksD-On Dec 15, 2022, at 7:48 AM, AndrewEllis93 ***@***.***> wrote:﻿
Currently it does not have that - but I don't think it would be too difficult to add, pretty much just invert all the Z coordinates, right?

**Comment by hoverdj** [comment]
Never mind. It magically started working. No idea what I did wrong last time. 
thanks for being willing to do it though. 
D-
