### ISSUE TITLE
Klipper smooth time max is 0.2 - might be good to have a note or something

### ISSUE THREAD

**Issue by PhilBaz** [AndrewEllis93/Pressure_Linear_Advance_Tool#14]
**Describe the bug**

Ran a test with smooth time up to .4. Klipper errors out in the middle of the print when it gets to the line that is over .2

**Klipper Error Message (if applicable)**

Error on 'SET_PRESSURE_ADVANCE SMOOTH_TIME=0.25 ; Set pressure advance': SMOOTH_TIME must have maximum of 0.2

Might be nice to either have max capped at .2 in the tool when testing smooth time. Or at least have a nice big asterisk note

**Comment by AndrewEllis93** [comment]
This should now throw an error when trying to exceed 0.2 with PA_SMOOTH enabled.
