### ISSUE TITLE
PA pattern not complete in cura

### ISSUE THREAD

**Issue by HTMOTS** [AndrewEllis93/Pressure_Linear_Advance_Tool#15]
Im trying to make a pa test but when i load it in cura it doesnt display all of the pattern. But it does print it.

**G-code File**
[PA gcode.txt](https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/files/10313955/PA.gcode.txt)

![picture of PA gcode in cura](https://user-images.githubusercontent.com/121552656/209805297-5d7663ee-4aa8-4652-ad4b-197fa0811169.PNG)

**Comment by AndrewEllis93** [comment]
Cura's gcode previewer has been really broken for a long time
Not an issue with the tool
