### ISSUE TITLE
Layer Count does not work

### ISSUE THREAD

**Issue by PaulDamian2** [AndrewEllis93/Pressure_Linear_Advance_Tool#23]
Setting Layer Count to any value doesn't do anything, always prints four layers.
Even in the generated GCODE file there is
; Print Settings:
;  - Line Width: 112.5 %
;  - Layer Count: 4
;  - Layer Height: 0.2 mm
;  - Print Speed: 50 mm/s
;  - Acceleration: Disabled
;  - Fan Speed: 0%
Even if I set it to 1

**Comment by gdsolar** [comment]
This does not work for me either. It seems to be locked at 4 layers no matter what.

**Comment by RenanAz** [comment]
+1 here. Always 4 layers.

**Comment by AndrewEllis93** [comment]
This should now be fixed. Thanks for reporting it.
