### ISSUE TITLE
increment smooth time instead issue

### ISSUE THREAD

**Issue by llecardu** [AndrewEllis93/Pressure_Linear_Advance_Tool#32]
When selecting increment smooth time instead, the PA and smooth time values are changed together. Perhaps i missed something. I am not seeing a way to set PA value and only adjust smooth time.

[smooth-time.zip](https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/files/13507074/smooth-time.zip)

**Comment by AndrewEllis93** [comment]
Your attached g-code file only shows the smooth time being set. Maybe you have a macro intercepting it / doing something funky?

![image](https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/assets/34943186/03ada89c-b7ad-46d2-82b7-b26590682a1d)
