### ISSUE TITLE
Unwanted "]" on Start Gcode klipper on pressure advance calibration tool (web)

### ISSUE THREAD

**Issue by Mac-EvoyING** [AndrewEllis93/Pressure_Linear_Advance_Tool#33]
**Bug Description**
An unwanted bracket is added to the hotend temperature during gcode generation, when the start gcode looks like this (focus: last 2 brackets).  See screenshots:
```
M104 S0
M140 S0
START_PRINT HEATER_BED=[first_layer_bed_temperature] HOTEND=[first_layer_temperature[initial_extruder]]
```

 which causes the hotend to inmediately shutdown after PA Test begins in klipper. Both bed and hotend temperatures are correctly parsed, however, the closing double brackets for the hotend seem not.

**Klipper Error Message **
No direct klipper error message is output, but the hotend shuts down inmediately after PA Calibration test starts, leading to an "extruder below minimum temperature" error. 

**G-code File**
Unsupported file type on Github.

**Screenshots**
![image](https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/assets/106494104/fee45082-4067-49da-9865-faa8c4fb21ec)

As a workaround, by removing one of the closing brackets (which is not correct), the GCODE generator seems to work just fine. No hotend shutdowns are experienced at all.

![image](https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/assets/106494104/4187a489-bdc2-4ee0-87ea-f51330cd20d2)

**Comment by AndrewEllis93** [comment]
Thanks for the pull request! I have not been keeping up here as much as I should - I fixed this after someone mentioned on Discord before seeing your PR sorry. But thank you regardless. It should be fixed now.
