### ISSUE TITLE
allow firmware retraction

### ISSUE THREAD

**Issue by oliof** [AndrewEllis93/Pressure_Linear_Advance_Tool#5]
**Is your feature request related to a problem? Please describe.**
Currently, the tool generates GCodes to retract and unretract. But some firmwares support Firmware Retract/Unretract with the G10/G11 Gcode commands

**Describe the solution you'd like**
Allow users to select Firmware Retract. This should inactivate the settings for Retract/Unretract

**Additional context**
 * RepRapFirmware: [G10](https://docs.duet3d.com/User_manual/Reference/Gcodes#g10-tool-temperature-setting), [G11](https://docs.duet3d.com/User_manual/Reference/Gcodes#g10-tool-temperature-setting]
 * Marlin also [G10/G11](https://marlinfw.org/docs/features/fwretract.html)
 * Klipper also [G10/G11](https://www.klipper3d.org/G-Codes.html#firmware_retraction)

Some slicers use M101/M102/M103, but it's best to ignore those IMO

**Comment by AndrewEllis93** [comment]
Firmware retract added. Tick "advanced mode" at the top.
