### ISSUE TITLE
start/end macros don't match klipper default names or parameters

### ISSUE THREAD

**Issue by strayr** [AndrewEllis93/Pressure_Linear_Advance_Tool#7]
Klipper [sample-macros.cfg](https://github.com/Klipper3d/klipper/blob/master/config/sample-macros.cfg) uses

```
[gcode_macro START_PRINT]
gcode:
    {% set BED_TEMP = params.BED_TEMP|default(60)|float %}
    {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(190)|float %}

# ...

[gcode_macro END_PRINT]
```

You are using different macro names and parameters, presumanbly becasue voron broke with convention?

**Comment by AndrewEllis93** [comment]
Yep. 
Everyone has completely different setups, it's nearly impossible to write a tool for Klipper because of that.
Most I've seen use PRINT_START / PRINT_END, but of course my experience is lopsided from spending most of my time in the Voron Discord.

**Comment by AndrewEllis93** [comment]
I added START_PRINT as an alternate (commented out)
