### ISSUE TITLE
PRINT_START macro is not regarded in gcode file

### ISSUE THREAD

**Issue by sebadue** [AndrewEllis93/Pressure_Linear_Advance_Tool#9]
Hi! Since some hours the generated gcode files always contain the start macro
`PRINT_START HOTEND=230 BED=70 CHAMBER=40 ; Start macro w/ temp params. Keep the variables!`

It does not change to my custom start script. This applies to all three settings "manual", "standalone" and "standalone + temp passing", the default script for that choice is exported, not the entered script.

**Comment by AndrewEllis93** [comment]
Might be a bug with the recent refactor - I will take a look, thanks

**Comment by AndrewEllis93** [comment]
Please try now.

**Comment by sebadue** [comment]
Thank you, it works now! Saved settings also work again.
